### ISSUE TITLE
Source Data Files

### ISSUE THREAD

**Issue by tiantorno** [PacktPublishing/Mastering-Qlik-Sense#2]
Hi there,

The Source Data files are not available here or on Packt. 

Chapter 7 page 175 references,  "TheCountryRevenue.xlsx source file consists of four sheets: Revenue, Time, Location, and Product". 

Can you please upload all the Source Data files for Mastering Qlik Sense.

Much Appreciated,

Tony

**Comment by tiantorno** [comment]
Or are the Source files all created via the inline script?

**Comment by simondachstr** [comment]
Hey Tian - we're in contact with the publisher to give us access to the repository.
